name: Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  JAVA_VERSION: '21'
  MAVEN_OPTS: -Xmx2g

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1) Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven

      # 2) Run tests
      - name: Run tests
        run: ./mvnw test

      # 3) Build the application
      - name: Build application
        run: ./mvnw clean package -DskipTests

      # 4) Upload the artifact (the Quarkus app package)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: quorch-package
          path: target/quarkus-app/